### ISSUE TITLE
Could you help with the installation please?

### ISSUE THREAD

**Issue by therohantilwani** [spandan114/Crowdfunding-DAPP#2]
I'm getting this error
![error](https://user-images.githubusercontent.com/36323861/235342650-6f951aec-6ba2-489b-a2dc-4ea9c0b8e80c.png)

**Comment by abhishekkumar11724** [comment]
Hello,
So, I was also getting this error in the starting.
But than I realized that since we are running our project on local machine and on a local blockchain, so we have to redeploy our contract every time we get start the project.
i.e., 
after running "npx hardhat node"
you have to redeploy the contract because, every time we stop the running blockchain, every data or contract on it get wiped out. So, run "npx hardhat run scripts/deploy.js --network localhost"

hope this helps :)

**Comment by Thiru-Malai** [comment]
Request to accept this pull request. This video tutorial of how to create a custom network will help people to understand and resolve this error.
